### PR TITLE
Remove root-owned temp files created by cromwell in evolver-test

### LINKED ISSUE #255: evolver_test create root directories outside of docker container
After running `make evolver_test` ends up creating root-owned directories run as a standard user  Somehow, these files are escaping the Docker container.  This appears to be related to cromwell.

files are under:
```
tmp_lfJBCoXdfW/cromwell-executions/
```

[root-files.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/4704730/root-files.txt)

### PR DESCRIPTION
**Pull request by glennhickey**
Couldn't find an option to make cromwell stop doing this, so adding a command in the teardown to remove them from docker. 

Will hopefully resolve #255

### CODE REVIEW

**Comment by diekhans** [comment]
This is still problematic, as any scribbling by a root process
outside of the container could get one's docker privilege
revoked.

Ideal would be a way to use container local disk so it goes away even
if it doesn't do the cleanup.

Although alternative is to only run cromwell tests at gitlab or
if explicitly requested.

**Comment by glennhickey** [comment]
Running cromwell from a container is probably doable.  But... that would
bring us up to 3 levels of docker for gitlab (gitlab base docker running
cromwell in docker that runs cactus in docker), which may be pushing our
luck.

Perhaps this is an issue to be raised with cromwell
https://github.com/broadinstitute/cromwell

**Comment by diekhans** [comment]
It is containers all the way down to the earth's core..

I was actually not suggesting another container, rather direct
the cromwell files to somewhere on the overlay file system.  That
is, anywhere other than /data

**Comment by glennhickey** [comment]
cromwell is run with `subprocess.check_call` from `cactus/tmp_xxx`.  Not sure how it's affecting /data or how to redirect to an overlay file system. 
https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/test/evolverTest.py#L89-L90

Anyway, if it's causing trouble for you and you want to make it opt-in (but run on gitlab) you have my blessing!

**Comment by diekhans** [comment]
I will take a look at it.  It seems like it should be straight-forward, just finding the right knob to set.

**Comment by glennhickey** [comment]
Travis didn't run but won't be affected by this change.  Will merge anyway.

**Pull request merged**
