### PR TITLE
Starting a branch to experiment with chaining local alignments to bet…

### PR DESCRIPTION
**Pull request by benedictpaten**
…ter select which alignments get included as anchors.

### CODE REVIEW

**Comment by benedictpaten** [comment]
weird, all the tests passed. right now we are using a max of 2 outgroups. @glennhickey ?

**Comment by glennhickey** [comment]
I ran `make evolver_test_local` five times.  2 outgroups is indeed better than 3, but both are noticeably worse than master. 

fwiw the baseline is from the pre-abpoa pipeline and the 0.4 threshold was set to let the abpoa pass comfortably.

```
# paf_chains with 2 outgroups (all pass)
Comparing mafcomp accuracy 0.855954,0.679743 to baseline accuracy 0.894622,0.706771 with threshold 0.04
Comparing mafcomp accuracy 0.855587,0.679013 to baseline accuracy 0.894622,0.706771 with threshold 0.04
Comparing mafcomp accuracy 0.85581,0.680307 to baseline accuracy 0.894622,0.706771 with threshold 0.04
Comparing mafcomp accuracy 0.855408,0.679456 to baseline accuracy 0.894622,0.706771 with threshold 0.04
Comparing mafcomp accuracy 0.855805,0.680034 to baseline accuracy 0.894622,0.706771 with threshold 0.04

# paf_chains with 3 outgroups (2 fail)
Comparing mafcomp accuracy 0.854799,0.679695 to baseline accuracy 0.894622,0.706771 with threshold 0.04
Comparing mafcomp accuracy 0.854357,0.679851 to baseline accuracy 0.894622,0.706771 with threshold 0.04
Comparing mafcomp accuracy 0.854359,0.680135 to baseline accuracy 0.894622,0.706771 with threshold 0.04
Comparing mafcomp accuracy 0.855474,0.679771 to baseline accuracy 0.894622,0.706771 with threshold 0.04
Comparing mafcomp accuracy 0.855737,0.68056 to baseline accuracy 0.894622,0.706771 with threshold 0.04

# master (all pass)
Comparing mafcomp accuracy 0.857049,0.686029 to baseline accuracy 0.894622,0.706771 with threshold 0.04
Comparing mafcomp accuracy 0.858794,0.685695 to baseline accuracy 0.894622,0.706771 with threshold 0.04
Comparing mafcomp accuracy 0.858131,0.684511 to baseline accuracy 0.894622,0.706771 with threshold 0.04
Comparing mafcomp accuracy 0.858452,0.685027 to baseline accuracy 0.894622,0.706771 with threshold 0.04
Comparing mafcomp accuracy 0.857313,0.686071 to baseline accuracy 0.894622,0.706771 with threshold 0.04
```

**Comment by benedictpaten** [comment]
Thanks, I'll figure it out. I agree, something is up

**Comment by benedictpaten** [comment]
I did some quick experiments to measure the performance of this branch, in reference to @glennhickey 's comment numbers above:

# Previously (Master?) (no-poa)
Mammals: 0.706771, 0.894622 

# Master - poa
Mammals: 0.686029, 0.857049


# paf chains - 1 outgroup - non-poa
Mammals: 0.695466, 0.870292, Primates: 0.987132, 0.998540
Mammals: 0.696771, 0.870749, Primates: 0.987159, 0.998559

# paf chains - 2 outgroup - non-poa
Mammals: 0.702636, 0.879245, Primates: 0.987029, 0.998495
Mammals: 0.702437, 0.879094, Primates: 0.987042, 0.998566

# paf chains - 3 outgroup - non-poa
Mammals: "0.702636, 0.879647, Primates: 0.987149, 0.998499
Mammals: 0.701924, 0.880395, Primates: 0.987156, 0.998554


# paf chains - 1 outgroup - poa
Mammals: 0.683393, 0.855566, Primates: 0.986308, 0.998057
Mammals: 0.681495, 0.854412, Primates: 0.986390, 0.998104

# paf chains - 2 outgroup - poa
Mammals: 0.683713, 0.857763, Primates: 0.986538, 0.998008
Mammals: 0.682190, 0.857300, Primates: 0.986642, 0.998139

# paf chains - 3 outgroup - poa
Mammals: 0.685124, 0.856435, Primates: 0.986459, 0.998028
Mammals: 0.684861, 0.857658, Primates: 0.986469, 0.998084 

So I conclude that performance is not worse with larger numbers of outgroups (if anything performance improves).

**Comment by glennhickey** [comment]
Here's that plot again with the master branch thrown in
evovler-mammls_1

**Pull request merged**
