### PR TITLE
Consolidated running

### PR DESCRIPTION
**Pull request by benedictpaten**
Start of a PR to streamliine running the core cactus processes on a single node.

### CODE REVIEW

**Comment by glennhickey** [comment]
Doh, I didn't mean to push those last 3 commits here.  Should be harmless enough though.

**Comment by benedictpaten** [comment]
Okay, I've added in the MUM based anchoring option for the bar alignments, for the evolver_mammals I get:

POA:  0.6058/0.7644 (recall/precision)
original: 0.7071/0.8942 
MUMs: 0.6882/0.8764

For the primates I get:
POA: 0.9854/0.9977
original: 0.9858/0.9987
MUMs: 0.9860/0.9985

So, MUMs are almost as good as original bar for primates and slightly worse for mammals. 

In terms of speed - the MUMs seems to be pretty fast, but not as fast as POA, probably by a factor of 5-6. I fixed an issue with the parameter parsing that actually speeds up the original bar a lot also, so, @glennhickey, we should actually try human-mouse with both the MUMs and original again.

@joelarmstrong , I note that for the Nature paper you quoted better numbers for Cactus, and that these numbers for original bar look close to the ones reported for the alignathon. I'm wondering if there has been a regression or a change in parameters? Can you look at the parameters file:

https://github.com/ComparativeGenomicsToolkit/cactus/blob/consolidated_running/src/cactus/cactus_progressive_config.xml

And let us know if there is some parameter change we haven't incorporated?

Cheers,

Benedict

**Comment by benedictpaten** [comment]
Also, @glennhickey, can you figure out why the build is broken? I thought I didn't change anything on that front.

**Comment by diekhans** [comment]
impl/pairwiseAligner.c:10:0: error: "_XOPEN_SOURCE" redefined [-Werror]


suggest doing:
#ifndef _XOPEN_SOURCE
# define _XOPEN_SOURCE 700
#endif

**Comment by benedictpaten** [comment]
Oops, found a small parameter issue with the MUM method, now the performance is better for mammals:

POA: 0.6058/0.7644 (recall/precision)
original: 0.7071/0.8942
MUMs: 0.70129/0.88967

For the primates I get:
POA: 0.9854/0.9977
original: 0.9858/0.9987
MUMs: 0.985894/0.998768

So, now the mum-based anchoring is almost the same for the primates and within 0.5% for the original. That seems like a good win to get rid of the flaky call outs to lastz for the bar.

**Comment by benedictpaten** [comment]
@glennhickey , Okay, made some progress on fixing up the poa params with evolver mammals and evolver primates. 

Evolver mammals:
non-poa: 0.699624/0.889130
new-poa: 0.654835/0.853910
old-poa: 0.606145/0.762824

Evolver primates:
non-poa: 0.986049/0.998758
new-poa: 0.985455/0.998245
old-poa: 0.985228/0.997737

I did this by trying to replicate the lastz parameters in abpoa. What would probably make it even better would be if the abpoa folks would implement the ability to do a scoring matrix, see: http://www.bx.psu.edu/~rsharris/lastz/README.lastz-1.04.03.html#options_scoring for substitutions, so that we could distinguish transitions from transversions. @glennhickey , can you talk to the abpoa people?

I also note that if I change the size of all the score parameters by a constant then performance changes, suggesting that there are some other cutoffs or parameters these changes are interacting with. If we can figure this out we can probably improve things further. It also crashes with some parameters I changed, suggesting some issues.

I committed these changes but I haven't switched on poa by default. Hopefully, we can improve it enough to make it a reasonable default for all. 

PS, parameters I changed are: 
partialOrderAlignmentBandConstant="100"
partialOrderAlignmentMatchScore="2"
partialOrderAlignmentMismatchPenalty="2"
partialOrderAlignmentGapOpenPenalty1="8"
partialOrderAlignmentGapExtensionPenalty1="1"
partialOrderAlignmentGapOpenPenalty2="24"
partialOrderAlignmentGapExtensionPenalty2="0.5"

**Comment by glennhickey** [comment]
Looks great!  Curious to see what effect it has on the humans (guess evolverPrimates is a pretty good idea).  abPoa's reading the scoring parameters into a matrix internally as far as I can tell, so allowing a full model to be specified should be pretty trivial.  I'll talk to them (can even hack it myself if we need).  

Note: this scoring matrix is of integers.  So your gap extension 2 is effectively 0.  Perhaps this is also related to some of the unexpected scaling behaviour you mention?

**Comment by glennhickey** [comment]
Changing the transition mismatch penalty to -1 (leaving transversions at -2) gives this.  Maybe just enough to be significant for mammals, but not enough to bridge the gap.  I see what you mean now about the scaling seeming wonky, though: just multiplying by 2 is enough to tank the stats, never mind using lastz's big scores. 

Evolver mammals:
non-poa: 0.699624/0.889130
new-poa: 0.654835/0.853910
**newer-poa: 0.67019/0.851539**
old-poa: 0.606145/0.762824

Evolver primates:
non-poa: 0.986049/0.998758
new-poa: 0.985455/0.998245
**newer-poa: 0.985359/0.997971**
old-poa: 0.985228/0.997737

**Comment by benedictpaten** [comment]
Interesting, I'd say that's a pretty good indication that the transitions/transversions distinction will def. improve the alignments. I think we ought to follow up with the abpoa folks to get the scaling of scores to not be wonky. My guess is that there is an overflow bug someplace. If we could scale the scores like lastz I suspect we'll be able to get even better results.

**Comment by benedictpaten** [comment]
also, it is obviously bad to have a 0 gap extension cost for the long gaps, so being able to scale things would allow us to charge properly for very long gaps

**Comment by glennhickey** [comment]
These parameters crash on the full pangenome.

**Comment by glennhickey** [comment]
For the record, here are [Erik's parameters from pggb](https://github.com/pangenome/pggb/blob/master/pggb#L23-L27).  Format is match,mismatch,open1,extend1,open2,extend2
```
# poa param suggestions from minimap2
# - asm5, --poa-params 1,19,39,3,81,1, ~0.1 divergence
# - asm10, --poa-params 1,9,16,2,41,1, ~1 divergence
# - asm20, --poa-params 1,4,6,2,26,1, ~5% divergence
poa_params="1,7,11,2,33,1"
```     

asm20 here gives `0.810218,0.654784` for mammals
poa_params        `0.829376,0.647672`

**Comment by benedictpaten** [comment]
Interesting. We need to get abpoa fixed so that we can use lastz scale
params and a proper substitution matrix. Right?

**Comment by benedictpaten** [comment]
I am no longer seeing the weird scaling of parameters issue. I just pushed a changed to make: 

		partialOrderAlignmentMatchScore="96"
		partialOrderAlignmentMismatchPenalty="90"
		partialOrderAlignmentGapOpenPenalty1="400"
		partialOrderAlignmentGapExtensionPenalty1="30"
		partialOrderAlignmentGapOpenPenalty2="1200"

(which is close to lastz, but without the transition/transversion distinction)

I get:

Evolver mammals:
non-poa: 0.699624/0.889130
new-poa: 0.654835/0.853910
newer-poa: 0.67019/0.851539
old-poa: 0.606145/0.762824
**this: 0.666065/0.847524**

Evolver primates:
non-poa: 0.986049/0.998758
new-poa: 0.985455/0.998245
newer-poa: 0.985359/0.997971
old-poa: 0.985228/0.997737
**this: 0.985485/0.998010**

**Comment by benedictpaten** [comment]
Oh, I note that the abpoa code is doing obnoxious amounts of logging on logLevel=INFO. That needs switching off.

**Pull request merged**
