### PR TITLE
Release process fixes

### PR DESCRIPTION
**Pull request by glennhickey**
These are mistakes I've caught when testing v1.1.0.  Speaking of mistakes, this was erroneously committed (now reverted) to master.

### CODE REVIEW

**Comment by diekhans** [comment]
I am surprised this is all you found :-)

thanks for cleaning up my mess.

**Comment by glennhickey** [comment]
The build scripts have been great.  The mistakes I'm talking about here are mostly ones I introduced in #288.

**Comment by diekhans** [comment]
Most of the content of the build scripts was taken from VG, only
putting them in scripts rather than instructions.  Might be nice
to work with them to converge on some common build stuff.

**Comment by glennhickey** [comment]
It all seems to be working fine, but the final release isn't running on terra due to a cryptic graphics driver issue.  Frustrating, as it ran through fine on a test I did right before tagging.  I think it's just cloud weather, but want to get it going before finalizing the release.

**Comment by glennhickey** [comment]
Hmm, the timing of [this](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=10.2-devel) seems to line up with where my trouble started:

```
10.2-devel           docker pull nvidia/cuda:10.2-devel
Last updated 11 hours ago by nvidiagitlab
```

**Comment by glennhickey** [comment]
For the record, Terra's own GPU demo script:

https://github.com/broadinstitute/cromwell/tree/50/centaur/src/main/resources/standardTestCases/gpu_on_papi

fails with the same type of error I'm seeing for Cactus, when run on these drivers as input `["418.87.00", "440.64.00"]`.  The first is from their documentation: https://cromwell.readthedocs.io/en/stable/RuntimeAttributes/#gpucount-gputype-and-nvidiadriverversion and the second is the one I've been using in Cactus for months without issue. 

The errors are 
```
Task gpu_cuda_image.get_machine_info:0:1 failed. The job was stopped before the command finished. PAPI error code 2. Execution failed: generic::unknown: installing drivers: container exited with unexpected exit code 1: + COS_DOWNLOAD_GCS=https://storage.googleapis.com/cos-tools + COS_KERNEL_SRC_GIT=https://chromium.googlesource.com/chromiumos/third_party/kernel + COS_KERNEL_SRC_ARCHIVE=kernel-src.tar.gz + TOOLCHAIN_URL_FILENAME=toolchain_url + TOOLCHAIN_ARCHIVE=toolchain.tar.xz + TOOLCHAIN_ENV_FILENAME=toolchain_env + CHROMIUMOS_SDK_GCS=https://storage.googleapis.com/chromiumos-sdk + ROOT_OS_RELEASE=/root/etc/os-release + KERNEL_SRC_DIR=/build/usr/src/linux + NVIDIA_DRIVER_VERSION=418.87.00 + NVIDIA_DRIVER_MD5SUM= + NVIDIA_INSTALL_DIR_HOST=/var/lib/nvidia + NVIDIA_INSTALL_DIR_CONTAINER=/usr/local/nvidia + ROOT_MOUNT_DIR=/root + CACHE_FILE=/usr/local/nvidia/.cache + LOCK_FILE=/root/tmp/cos_gpu_installer_lock + LOCK_FILE_FD=20 + set +x [INFO 2020-07-31 15:03:28 UTC] Checking if this is the only cos-gpu-installer that is running. [INFO 2020-07-31 15:03:28 UTC] Running on COS build id 12871.1174.0 [INFO 2020-07-31 15:03:28 UTC] Checking if third party kernel modules can be installed [INFO 2020-07-31 15:03:28 UTC] Checking cached version [INFO 2020-07-31 15:03:28 UTC] Cache file /usr/local/nvidia/.cache not found. [INFO 2020-07-31 15:03:28 UTC] Did not find cached version, building the drivers... [INFO 2020-07-31 15:03:28 UTC] Downloading GPU installer ... [INFO 2020-07-31 15:03:30 UTC] Downloading from https://storage.googleapis.com/nvidia-drivers-us-public/tesla/418.87.00/NVIDIA-Linux-x86_64-418.87.00.run ls: cannot access '/build/usr/src/linux': No such file or directory [INFO 2020-07-31 15:03:32 UTC] Kernel sources not found locally, downloading [INFO 2020-07-31 15:03:32 UTC] Kernel source archive download URL: https://storage.googleapis.com/cos-tools/12871.1174.0/kernel-src.tar.gz real 0m1.728s user 0m0.192s sys 0m0.387s [INFO 2020-07-31 15:03:46 UTC] Setting up compilation environment [INFO 2020-07-31 15:03:46 UTC] Obtaining toolchain_env file from https://storage.googleapis.com/cos-tools/12871.1174.0/toolchain_env real 0m0.843s user 0m0.016s sys 0m0.004s [INFO 2020-07-31 15:03:47 UTC] Downloading toolchain from https://storage.googleapis.com/cos-tools/12871.1174.0/toolchain.tar.xz real 0m6.971s user 0m0.576s sys 0m1.280s [INFO 2020-07-31 15:04:54 UTC] Configuring environment variables for cross-compilation [INFO 2020-07-31 15:04:54 UTC] Configuring installation directories [INFO 2020-07-31 15:04:54 UTC] Updating container's ld cache [INFO 2020-07-31 15:04:56 UTC] Configuring kernel sources [INFO 2020-07-31 15:05:37 UTC] Modifying kernel version magic string in source files [INFO 2020-07-31 15:05:37 UTC] Running Nvidia installer ERROR: The kernel module failed to load, because it was not signed by a key that is trusted by the kernel. Please try installing the driver again, and set the --module-signing-secret-key and --module-signing-public-key options on the command line, or run the installer in expert mode to enable the interactive module signing prompts. ERROR: Unable to load the kernel module 'nvidia.ko'. This happens most frequently when this kernel module was built against the wrong or improperly configured kernel sources, with a version of gcc that differs from the one used to build the target kernel, or if another driver, such as nouveau, is present and prevents the NVIDIA kernel module from obtaining ownership of the NVIDIA GPU(s), or no NVIDIA GPU installed in this system is supported by this NVIDIA Linux graphics driver release. Please see the log entries 'Kernel module load error' and 'Kernel messages' at the end of the file '/usr/local/nvidia/nvidia-installer.log' for more information. ERROR: Installation has failed. Please see the file '/usr/local/nvidia/nvidia-installer.log' for details. You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.
```
```
Task gpu_cuda_image.get_machine_info:1:1 failed. The job was stopped before the command finished. PAPI error code 2. Execution failed: generic::unknown: installing drivers: container exited with unexpected exit code 1: + COS_DOWNLOAD_GCS=https://storage.googleapis.com/cos-tools + COS_KERNEL_SRC_GIT=https://chromium.googlesource.com/chromiumos/third_party/kernel + COS_KERNEL_SRC_ARCHIVE=kernel-src.tar.gz + TOOLCHAIN_URL_FILENAME=toolchain_url + TOOLCHAIN_ARCHIVE=toolchain.tar.xz + TOOLCHAIN_ENV_FILENAME=toolchain_env + CHROMIUMOS_SDK_GCS=https://storage.googleapis.com/chromiumos-sdk + ROOT_OS_RELEASE=/root/etc/os-release + KERNEL_SRC_DIR=/build/usr/src/linux + NVIDIA_DRIVER_VERSION=440.64.00 + NVIDIA_DRIVER_MD5SUM= + NVIDIA_INSTALL_DIR_HOST=/var/lib/nvidia + NVIDIA_INSTALL_DIR_CONTAINER=/usr/local/nvidia + ROOT_MOUNT_DIR=/root + CACHE_FILE=/usr/local/nvidia/.cache + LOCK_FILE=/root/tmp/cos_gpu_installer_lock + LOCK_FILE_FD=20 + set +x [INFO 2020-07-31 15:03:29 UTC] Checking if this is the only cos-gpu-installer that is running. [INFO 2020-07-31 15:03:29 UTC] Running on COS build id 12871.1174.0 [INFO 2020-07-31 15:03:29 UTC] Checking if third party kernel modules can be installed [INFO 2020-07-31 15:03:29 UTC] Checking cached version [INFO 2020-07-31 15:03:29 UTC] Cache file /usr/local/nvidia/.cache not found. [INFO 2020-07-31 15:03:29 UTC] Did not find cached version, building the drivers... [INFO 2020-07-31 15:03:29 UTC] Downloading GPU installer ... [INFO 2020-07-31 15:03:30 UTC] Downloading from https://storage.googleapis.com/nvidia-drivers-us-public/tesla/440.64.00/NVIDIA-Linux-x86_64-440.64.00.run ls: cannot access '/build/usr/src/linux': No such file or directory [INFO 2020-07-31 15:03:33 UTC] Kernel sources not found locally, downloading [INFO 2020-07-31 15:03:33 UTC] Kernel source archive download URL: https://storage.googleapis.com/cos-tools/12871.1174.0/kernel-src.tar.gz real 0m1.147s user 0m0.223s sys 0m0.435s [INFO 2020-07-31 15:03:47 UTC] Setting up compilation environment [INFO 2020-07-31 15:03:47 UTC] Obtaining toolchain_env file from https://storage.googleapis.com/cos-tools/12871.1174.0/toolchain_env real 0m0.734s user 0m0.016s sys 0m0.004s [INFO 2020-07-31 15:03:48 UTC] Downloading toolchain from https://storage.googleapis.com/cos-tools/12871.1174.0/toolchain.tar.xz real 0m6.453s user 0m0.595s sys 0m1.237s [INFO 2020-07-31 15:04:54 UTC] Configuring environment variables for cross-compilation [INFO 2020-07-31 15:04:54 UTC] Configuring installation directories [INFO 2020-07-31 15:04:54 UTC] Updating container's ld cache [INFO 2020-07-31 15:04:56 UTC] Configuring kernel sources [INFO 2020-07-31 15:05:38 UTC] Modifying kernel version magic string in source files [INFO 2020-07-31 15:05:38 UTC] Running Nvidia installer ERROR: The kernel module failed to load, because it was not signed by a key that is trusted by the kernel. Please try installing the driver again, and set the --module-signing-secret-key and --module-signing-public-key options on the command line, or run the installer in expert mode to enable the interactive module signing prompts. ERROR: Unable to load the kernel module 'nvidia.ko'. This happens most frequently when this kernel module was built against the wrong or improperly configured kernel sources, with a version of gcc that differs from the one used to build the target kernel, or if another driver, such as nouveau, is present and prevents the NVIDIA kernel module from obtaining ownership of the NVIDIA GPU(s), or no NVIDIA GPU installed in this system is supported by this NVIDIA Linux graphics driver release. Please see the log entries 'Kernel module load error' and 'Kernel messages' at the end of the file '/usr/local/nvidia/nvidia-installer.log' for more information. ERROR: Installation has failed. Please see the file '/usr/local/nvidia/nvidia-installer.log' for details. You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.	
```

So I guess it's just bad luck that the cloud decided to break literally just as I created and tested a new release image.

**Comment by glennhickey** [comment]
Terra has confirmed the GPU issue, and will post updates here:

https://support.terra.bio/hc/en-us/community/posts/360072053131-Tasks-with-NVIDIA-GPUs-fail-with-PAPI-error-code-2

**Pull request merged**
