### PR TITLE
Get ready for gitlab

### PR DESCRIPTION
**Pull request by glennhickey**
This (or something similar) would be a great start to gitlab integration tests.  It currently runs in about 1.5 hours on my 8 core / 32G desktop.  I bet it would be similar on 4 cores / 8G.  About 32G disk should be fine.  If any toil folks @DailyDreaming @adamnovak @diekhans  would be able to hook this up, I'd be much obliged.

### CODE REVIEW

**Comment by glennhickey** [comment]
Thanks @DailyDreaming.  I've updated the settings, accordingly.  Am also seeing the gitlab icon turn up here, so there must be some progress.  Let me know if there's anything else I can do (though I'm going to be awayish for a bit).  @adamnovak I'm okay with disabling the Docker version of the test for the time being if it's going to cause docker-in-docker trouble.

**Comment by glennhickey** [comment]
@DailyDreaming @adamnovak Gitlab/Kubernetes seems to be working for vg and toil-vg.  But there is still a problem here with Cactus where it [can't find a runner](https://ucsc-ci.com/comparativegenomicstoolkit/cactus/-/jobs/44581).  And the [link through to the runners page](https://ucsc-ci.com/comparativegenomicstoolkit/cactus/runners#js-runners-settings) doesn't exist.  Would one of you mind please taking a look?  It seems to me we're pretty close to getting this up and going.  thanks!

**Comment by adamnovak** [comment]
The runners page link
https://ucsc-ci.com/comparativegenomicstoolkit/cactus/-/settings/ci_cd#js-runners-settings
works for me. But it looks like you weren't a member of the cactus
project or its parent ComparativeGenomicsToolkit group on Gitlab. I've
added you as a maintainer for the group, so now you should be allowed
to see the project settings.

I think it can't find a runner because we don't actually have any
runners configured to run jobs for the whole instance. We've been
setting them up at group and project levels, to run jobs just for that
group or project. So the Toil runner runs jobs for the
DataBiosphere/toil project in the toil Kubernetes namespace, and the
vg runner runs jobs for the vgteam group (and its vg and toil-vg
projects) in the vg Kubernetes namespace.

Cactus would then need its own runner, either for the whole
ComparativeGenomicsToolkit group or for just the
ComparativeGenomicsToolkit/cactus project, set up accoridng to
https://github.com/DataBiosphere/toil/wiki/Gitlab-CI-Autoscaling-Setup#kubernetes-based-setup
in whatever namespace on Kubernetes we want to run the Cactus CI jobs
in.

Alternately, we could move the project on Gitlab under a group that
already has a runner, or we could set up a runner for the whole
instance across all projects, somewhere. Either of those would save us
another pod sitting around on Kubernetes forever waiting for Gitlab
jobs to come in so it can schedule them.

**Comment by glennhickey** [comment]
Thanks, I see.  If it's not too much of a hassle to setup of a `ComparativeGenomicsToolkit` runner, I guess that would be the most consistent with the status quo (of maximally isolating everyone on kubernetes).  Personally speaking, I certainly wouldn't have anything against just adding cactus to an existing namespace for gitlab/kubernetes though.

**Comment by adamnovak** [comment]
Does Cactus have a Kubernetes namespace for itself yet?

**Pull request merged**
