### PR TITLE
WIP: Option to run cactus-prepare commands in Toil

### PR DESCRIPTION
**Pull request by glennhickey**
This kind of follows the `--wdl` logic but instead of making a WDL workflow, the commands are chained together in a Toil run.  So we have a top-level toil script (`cactus-prepare-toil`) running nested toil-scripts (`cactus-blast`, `cactus-align`, etc).  

The twisted logic behind this comes from trying to shoehorn cactus into working on our kubernetes cluster.  Toil's kubernetes batch system cannot schedule too many jobs, and the nodes are big enough that they can tackle fairly large subproblems.  

I guess this logic could apply to other environments where scheduling jobs is expensive, though, so far, I think WDL/cromwell is easier to work with than toil-in-toil.

### CODE REVIEW

**Comment by glennhickey** [comment]
I'm having trouble getting this going on kubernetes.  I log into a pod and install cactus with
```
git clone https://github.com/ComparativeGenomicsToolkit/cactus.git --recursive --branch toil-prepare
virtualenv -p python3.6 venv
. venv/bin/activate
pip install -U -r toil-requirement.txt
pip install -U .
```
Then I run the pipeline with
```
cactus-prepare-toil aws:us-west-2:glennhickey-jobstore examples/evolverMammals.txt   --binariesMode singularity --batchSystem kubernetes --realTimeLogging --outHal evolverMammals.hal --defaultMemory 16 --defaultCores 2 --defaultDisk 30
```
But it gives me this error when it tries to run the first job:
```
ModuleNotFoundError: No module named 'cactus'
```
@adamnovak can you see anything I'm doing wrong? 

log context:
```
[2020-08-20T19:12:07+0000] [MainThread] [I] [botocore.credentials] Found credentials in shared credentials file: ~/.aws/credentials
[2020-08-20T19:12:07+0000] [MainThread] [I] [botocore.credentials] Found credentials in shared credentials file: ~/.aws/credentials
[2020-08-20T19:12:07+0000] [MainThread] [I] [botocore.credentials] Found credentials in shared credentials file: ~/.aws/credentials
[2020-08-20T19:12:10+0000] [MainThread] [I] [toil] Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
[2020-08-20T19:12:10+0000] [MainThread] [I] [toil] Using default docker name of toil as TOIL_DOCKER_NAME is not set.
[2020-08-20T19:12:10+0000] [MainThread] [I] [toil] Using default docker appliance of quay.io/ucsc_cgl/toil:4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b-py3.6 as TOIL_APPLIANCE_SELF is not set.
[2020-08-20T19:12:19+0000] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host glenn-cactus-int-5ssxt.
[2020-08-20T19:12:19+0000] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2020-08-20T19:12:20+0000] [MainThread] [I] [toil.leader] Issued job 'Job' 25bb91b9-479d-4f86-a41d-a9a785a5ad0e with job batch system ID: 0 and cores: 2, disk: 30.0 , and memory: 16.0 
[2020-08-20T19:12:22+0000] [MainThread] [I] [toil.leader] 1 jobs are running, 0 jobs are issued and waiting to run
[2020-08-20T19:12:23+0000] [Thread-67 ] [W] [toil.statsAndLogging] Got message from job at time 08-20-2020 19:12:23: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job 97ecea65-0a76-4fb0-a5b9-
b3e4fe813008 used 13653.33% (4.0 KB [4096B] used, 30.0 B [30B] requested) at the end of its run.
[2020-08-20T19:12:23+0000] [MainThread] [I] [toil.batchSystems.kubernetes] REASON: Completed Exit Code: 0
[2020-08-20T19:12:26+0000] [MainThread] [I] [toil.leader] Job ended: 'Job' 25bb91b9-479d-4f86-a41d-a9a785a5ad0e
[2020-08-20T19:12:26+0000] [MainThread] [I] [toil.leader] Issued job 'toil_call_preprocess' c75850dc-571e-4ee1-9e6b-a7817ec4d42f with job batch system ID: 1 and cores: 2, disk: 30.0 G, and memory: 16.0 G
[2020-08-20T19:12:26+0000] [MainThread] [I] [toil.leader] Issued job 'toil_call_preprocess' 6f5b0f95-0d9c-4c7a-906c-7a61e244ac9e with job batch system ID: 2 and cores: 2, disk: 30.0 G, and memory: 16.0 G
[2020-08-20T19:12:26+0000] [MainThread] [I] [toil.leader] Issued job 'toil_call_preprocess' 76daaa6b-2677-4fda-9cd9-3a4c9c3033d1 with job batch system ID: 3 and cores: 2, disk: 30.0 G, and memory: 16.0 G
[2020-08-20T19:12:26+0000] [MainThread] [I] [toil.leader] Issued job 'toil_call_preprocess' feb8f5c4-5ebe-4602-a2a0-da7b5d46d3cf with job batch system ID: 4 and cores: 2, disk: 30.0 G, and memory: 16.0 G
[2020-08-20T19:12:26+0000] [MainThread] [I] [toil.leader] Issued job 'toil_call_preprocess' 718b426f-36a5-40af-b8a8-e0c9fe06cf89 with job batch system ID: 5 and cores: 2, disk: 30.0 G, and memory: 16.0 G
[2020-08-20T19:12:30+0000] [MainThread] [I] [toil.batchSystems.kubernetes] REASON: Error Exit Code: 1
[2020-08-20T19:12:30+0000] [MainThread] [W] [toil.batchSystems.kubernetes] Log from failed pod: [2020-08-20T19:12:28+0000] [MainThread] [D] [toil.batchSystems.kubernetes] Starting executor
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.batchSystems.kubernetes] Adopting environment: dict_keys(['TOIL_RT_LOGGING_ADDRESS', 'TOIL_RT_LOGGING_LEVEL'])
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.batchSystems.kubernetes] Preparing system for resource download
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.lib.threading] Joining arena /var/lib/toil/f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-members
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.lib.threading] PID 1 acquiring mutex /var/lib/toil/toil-mutex-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-lock
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.lib.threading] PID 1 now holds mutex /var/lib/toil/toil-mutex-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-lock
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.lib.threading] PID 1 releasing mutex /var/lib/toil/toil-mutex-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-lock
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.lib.threading] Now in arena /var/lib/toil/f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-members
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.batchSystems.kubernetes] Invoking command: '_toil_worker toil_call_preprocess aws:us-west-2:glennhickey-jobstore 6f5b0f95-0d9c-4c7a-906c-7a61e244ac9e'
[2020-08-20T19:12:29+0000] [MainThread] [I] [toil.worker] Redirecting logging to /var/lib/toil/node-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-4ad9c8e3b64c0936af8834905f342da0/tmp4ncmudt0/worker_log.txt
[2020-08-20T19:12:30+0000] [MainThread] [D] [toil.lib.threading] Leaving arena /var/lib/toil/f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-members
[2020-08-20T19:12:30+0000] [MainThread] [D] [toil.lib.threading] PID 1 acquiring mutex /var/lib/toil/toil-mutex-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-lock
[2020-08-20T19:12:30+0000] [MainThread] [D] [toil.lib.threading] PID 1 now holds mutex /var/lib/toil/toil-mutex-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-lock
[2020-08-20T19:12:30+0000] [MainThread] [D] [toil.lib.threading] PID 1 releasing mutex /var/lib/toil/toil-mutex-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-lock
[2020-08-20T19:12:30+0000] [MainThread] [D] [toil.lib.threading] Now out of arena /var/lib/toil/f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-members
[2020-08-20T19:12:30+0000] [MainThread] [D] [toil.batchSystems.kubernetes] Cleaning up resources
[2020-08-20T19:12:30+0000] [MainThread] [D] [toil.batchSystems.kubernetes] Shutting down

[2020-08-20T19:12:30+0000] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'toil_call_preprocess' 6f5b0f95-0d9c-4c7a-906c-7a61e244ac9e
[2020-08-20T19:12:30+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'toil_call_preprocess' 6f5b0f95-0d9c-4c7a-906c-7a61e244ac9e
[2020-08-20T19:12:31+0000] [MainThread] [W] [toil.leader] Log from job 6f5b0f95-0d9c-4c7a-906c-7a61e244ac9e follows:
=========>
        [2020-08-20T19:12:29+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2020-08-20T19:12:29+0000] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host glenn-toil-df222b16-7d41-401d-b0a2-2296f48c00c9-2-s56rh.
        [2020-08-20T19:12:29+0000] [MainThread] [E] [toil.resource] Failed to import user module ModuleDescriptor(dirPath='/work/cactus/venv/lib/python3.6/site-packages', name='cactus.progressive.cactus_prepare', fromVirtualEnv=True) from sys.path (['/usr/local/bin', '/usr/lib/python36
.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/work/cactus/venv/lib/python3.6/site-packages']).
        Traceback (most recent call last):
          File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 352, in workerScript
            job = Job._loadJob(jobGraph.command, jobStore)
          File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 919, in _loadJob
            userModule = cls._loadUserModule(userModule)
          File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 896, in _loadUserModule
            return userModule.load()
          File "/usr/local/lib/python3.6/dist-packages/toil/resource.py", line 611, in load
            return importlib.import_module(module.name)
          File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
            return _bootstrap._gcd_import(name[level:], package, level)
          File "<frozen importlib._bootstrap>", line 994, in _gcd_import
          File "<frozen importlib._bootstrap>", line 971, in _find_and_load
          File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
          File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
          File "<frozen importlib._bootstrap>", line 994, in _gcd_import
          File "<frozen importlib._bootstrap>", line 971, in _find_and_load
          File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
          File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
          File "<frozen importlib._bootstrap>", line 994, in _gcd_import
          File "<frozen importlib._bootstrap>", line 971, in _find_and_load
          File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
        ModuleNotFoundError: No module named 'cactus'
        [2020-08-20T19:12:29+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host glenn-toil-df222b16-7d41-401d-b0a2-2296f48c00c9-2-s56rh
<=========
[2020-08-20T19:12:31+0000] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'toil_call_preprocess' 6f5b0f95-0d9c-4c7a-906c-7a61e244ac9e with ID 6f5b0f95-0d9c-4c7a-906c-7a61e244ac9e to 1
[2020-08-20T19:12:31+0000] [MainThread] [I] [toil.leader] Issued job 'toil_call_preprocess' 6f5b0f95-0d9c-4c7a-906c-7a61e244ac9e with job batch system ID: 6 and cores: 2, disk: 30.0 G, and memory: 16.0 G
[2020-08-20T19:12:31+0000] [MainThread] [W] [toil.batchSystems.kubernetes] Log from failed pod: [2020-08-20T19:12:28+0000] [MainThread] [D] [toil.batchSystems.kubernetes] Starting executor
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.batchSystems.kubernetes] Adopting environment: dict_keys(['TOIL_RT_LOGGING_ADDRESS', 'TOIL_RT_LOGGING_LEVEL'])
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.batchSystems.kubernetes] Preparing system for resource download
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.lib.threading] Joining arena /var/lib/toil/f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-members
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.lib.threading] PID 1 acquiring mutex /var/lib/toil/toil-mutex-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-lock
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.lib.threading] PID 1 now holds mutex /var/lib/toil/toil-mutex-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-lock
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.lib.threading] PID 1 releasing mutex /var/lib/toil/toil-mutex-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-lock
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.lib.threading] Now in arena /var/lib/toil/f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-members
[2020-08-20T19:12:28+0000] [MainThread] [D] [toil.batchSystems.kubernetes] Invoking command: '_toil_worker toil_call_preprocess aws:us-west-2:glennhickey-jobstore c75850dc-571e-4ee1-9e6b-a7817ec4d42f'
[2020-08-20T19:12:29+0000] [MainThread] [I] [toil.worker] Redirecting logging to /var/lib/toil/node-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-4ad9c8e3b64c0936af8834905f342da0/tmp9uirwscs/worker_log.txt
[2020-08-20T19:12:29+0000] [MainThread] [D] [toil.lib.threading] Leaving arena /var/lib/toil/f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-members
[2020-08-20T19:12:29+0000] [MainThread] [D] [toil.lib.threading] PID 1 acquiring mutex /var/lib/toil/toil-mutex-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-lock
[2020-08-20T19:12:29+0000] [MainThread] [D] [toil.lib.threading] PID 1 now holds mutex /var/lib/toil/toil-mutex-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-lock
[2020-08-20T19:12:29+0000] [MainThread] [D] [toil.lib.threading] PID 1 releasing mutex /var/lib/toil/toil-mutex-f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-lock
[2020-08-20T19:12:29+0000] [MainThread] [D] [toil.lib.threading] Now out of arena /var/lib/toil/f9a35eb8-88b3-4b3f-a8ce-235f7d03206a-kube-executor-arena-members
[2020-08-20T19:12:29+0000] [MainThread] [D] [toil.batchSystems.kubernetes] Cleaning up resources
[2020-08-20T19:12:29+0000] [MainThread] [D] [toil.batchSystems.kubernetes] Shutting down

```

**Comment by adamnovak** [comment]
Hm. Could be a Toil bug I guess.

How does your setup differ from Toil's Cactus integration test that works?

**Comment by glennhickey** [comment]
Thanks, knowing there's a toil test is handy.  And indeed, I am able to run something akin to the `cactus` command I see in its log https://ucsc-ci.com/databiosphere/toil/-/jobs/58862/raw.  But when I try to run `cactus-prepare-toil` instead of `cactus` then I get my module not found error.   Perhaps it's related to it [not hooking into a main() function](https://github.com/ComparativeGenomicsToolkit/cactus/blob/toil-prepare/setup.py#L51)?

**Comment by glennhickey** [comment]
I tried renaming to `main`, and even renaming the command `cactus` instead of `cactus-prepare-toil` with no luck.  So there must really be something in this particular script that I'm doing to displease cactus.

**Comment by adamnovak** [comment]
OK @glennhickey, I think I found the problem.

I finally got around to reproducing this. `cactus` has this in the log:

```
[2020-08-31T17:34:39-0700] [MainThread] [D] [toil.common] Saving user script ModuleDescriptor(dirPath='/public/home/anovak/build/toil/venv3/lib/python3.6/site-packages', name='cactus.progressive.cactus_progressive', fromVirtualEnv=True) as a resource
```

But `cactus-prepare-toil` has this:

```
[2020-08-31T17:42:39-0700] [MainThread] [D] [toil.common] User script ModuleDescriptor(dirPath='/public/home/anovak/build/toil/src', name='toil.job', fromVirtualEnv=False) belongs to Toil. No need to auto-deploy it.
[2020-08-31T17:42:39-0700] [MainThread] [D] [toil.common] No user script to auto-deploy.
```

Your problem is that your root job is a `toil.job.Job` that you're wiring up statically and not a derived class. Toil guesses what virtualenv if any it needs to deploy by looking at the root job of the workflow and what module it is from, when really it probably needs to look through the whole graph of jobs attached to that root job.

Make your root job a class (or function) that you define, and it should magically start working.

**Comment by glennhickey** [comment]
Thanks @adamnovak!

**Pull request merged**
