### PR TITLE
[WIP] Big XML Cleanup

### LINKED ISSUE #189: Move file paths out of XML!
There's a bit of technical debt (thanks in no small part to me!) that needs paying back with regards to all the various XML configuration files.  The main problem is that paths are being embedded inside them.  Often as toil IDs cast to strings.  And to make matters worse, XML files contain paths to other XML files.  

This has already cost me a ton of time just in trying to hack changes into the existing functionality, ex #178 #186.  Before any further changes, I think we need to at a minimum
* remove all paths out of the XML files and wrappers, and pass toil IDs around explicitly
Ideally we'd also
* Flatten everything into two structures
     * configuraiton : I tihnk this can stay unchanged as config.xml / ConfigWrapper
     * everything else : flatten experiment and project and everything in between into one structure.  and never pass around a path to this structure -- rely 100% on toil pickling to pass it from job to job as a parameter.  Let it produce strings of XML as needed on the fly by the various `cactus_` command lines.

### PR DESCRIPTION
**Pull request by glennhickey**
This PR cuts out all notions of "projects" and "experiments", and any notion of parameters passed via files.  As expected, it escalated into a pretty substantial refactor of cactus_workflow.py and cactus_progressive.py.

Resolves #189

Still a few things to do before merging (even after shaking out CI tests):
* try on big tree (and implement follow-on schedule jobs)
* bigger pangenome tests

### CODE REVIEW

**Comment by benedictpaten** [comment]
do you want to merge this into the paf_chains branch now, or wait? Looks great.

**Comment by glennhickey** [comment]
There seems to be a problem scheduling big trees, which I think I can fix by deleting more code.  Will ping back here when that's done and it's ready to merge -- should be very soon.

**Comment by glennhickey** [comment]
@benedictpaten OK it's ready to merge!

**Comment by glennhickey** [comment]
Also, please merge this one too while you're at it:
https://github.com/ComparativeGenomicsToolkit/cactus/pull/602

**Pull request merged**
