### PR TITLE
[experimental] add RED as a preprocessor masking option

### PR DESCRIPTION
**Pull request by glennhickey**
[RED](https://doi.org/10.1186/s12859-015-0654-5) is a fairly general purpose repeat masker. I'm interested in it because in my (very limited) tests so far it is fast and sensitive without specifying any parameters.  

The current lastz-based repeatmasking, on the other hand, is causing problems with newer assemblies.  Even with RepeatMasked/Modelled input genomes, it's both very slow and, apparently insufficient on some genomes.  This leads to giant pairwise alignments (from all-to-all repeat copy collapses) which bog down bar to the point of crashing (perhaps too many rows into abpoa? I haven't confirmed) if the paffy chaining stuff beforehand doesn't run out of memory. 

In theory, this shouldn't happen since the lastz masker should be able to filter out anything to repetitive in lastz (the parameters are a bit different but the seeding should be the same).  I don't know if `proportionToSample="0.2"` is at play here, or it boils down to the difference in parameters, but something isn't working out. 

Anyway, there's not much to lose by trying another masker -- hence this branch.  Red's fast enough that it can be added in before lastz with negligible cost (which is the default logic as I write this).  I think it will be merge-worthy if we can then drop lastz without noticing a decrease in alignment quality (big win in running time), but it will also be worth it if either alone or combined with lastz it helps get some of these tricker genomes through the pipeline.

### CODE REVIEW

**Comment by glennhickey** [comment]
Some data from the zoonomia "10"-way test alignment.  In all cases Red masks considerably more than lastz.  It doesn't get everything lastz finds (as evidenced by the BOTH column being a bit bigger), but I think using it alone should be fine for most cases.  Just need to run a few bigger tests (if the cluster ever frees up) to make sure sensitivity isn't reduced.  Will also check to see where some of the added masking is coming from. 


<body>

  | INPUT | LASTZ | RED | BOTH
-- | -- | -- | -- | --
bosTau8 | 0.490842 | 0.507322 | 0.534462 | 0.540855
canFam3 | 0.434422 | 0.441001 | 0.52214 | 0.523653
dipOrd1 | 0.386965 | 0.533592 | 0.542276 | 0.562005
equCab3 | 0.446994 | 0.458693 | 0.557123 | 0.559708
felCat8 | 0.452909 | 0.464814 | 0.525026 | 0.52738
hg38_without_alts | 0.545004 | 0.556511 | 0.583615 | 0.595528
mm10 | 0.467471 | 0.496097 | 0.515172 | 0.519506
panTro6 | 0.540358 | 0.550028 | 0.584369 | 0.586595
rheMac8 | 0.556622 | 0.565577 | 0.616582 | 0.618699
rn6 | 0.460768 | 0.483429 | 0.517443 | 0.52143
susScr11 | 0.459816 | 0.471296 | 0.535106 | 0.538855
tupChi1 | 0.429745 | 0.443084 | 0.506009 | 0.513617


</body>

</html>

**Comment by glennhickey** [comment]
Here are stats for the 8-way t2t apes alignment

hs1 coverage with lastz masking
```
GCA_028858775.2, 904679, 26398, 14845, 10558, 7648, 5600, 4456, 3835, 3287, 2935, 2333, 1847, 1491, 1273, 1110, 1078, 943, 852, 767, 560, 311, 306, 268, 267, 260, 259, 225, 223, 194, 189, 184, 183, 182, 181, 176, 160, 30, 19, 9, 9, 8, 8, 0, 0, 0, 0, 0
GCA_028878055.2, 834107, 16858, 6329, 3952, 2712, 2041, 1495, 1207, 915, 827, 746, 665, 620, 559, 533, 491, 491, 491, 486, 472, 445, 420, 352, 330, 310, 240, 235, 213, 213, 211, 209, 155, 136, 119, 119, 113, 110, 109, 106, 106, 106, 106, 105, 97, 62, 54, 3
GCA_028885625.2, 873401, 23453, 11500, 8163, 6183, 4595, 3579, 2464, 2007, 1660, 1318, 1130, 995, 973, 884, 822, 708, 652, 552, 515, 332, 270, 188, 183, 128, 88, 76, 59, 16, 11, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
GCA_028885655.2, 873616, 23450, 11110, 7454, 5565, 4406, 3755, 3157, 2635, 2010, 1580, 1338, 1079, 909, 831, 809, 774, 705, 644, 604, 493, 474, 440, 420, 401, 368, 342, 270, 254, 222, 196, 164, 133, 128, 128, 124, 118, 105, 77, 52, 1, 0, 0, 0, 0, 0, 0
GCA_029281585.2, 898540, 32974, 18157, 12538, 9281, 7001, 5716, 4534, 3423, 2676, 2288, 2021, 1839, 1674, 1391, 1340, 1232, 1067, 957, 894, 786, 690, 503, 493, 453, 430, 427, 343, 275, 145, 130, 109, 80, 42, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
GCA_029289425.2, 904715, 26311, 15115, 10246, 7569, 5579, 4351, 3442, 2868, 2500, 2149, 1549, 1360, 1194, 879, 685, 558, 508, 495, 438, 414, 353, 228, 188, 48, 33, 17, 16, 16, 16, 16, 16, 16, 16, 15, 15, 12, 9, 9, 9, 9, 9, 9, 8, 8, 6, 0
hg38, 928939, 31630, 10339, 6150, 4144, 2943, 2047, 1315, 532, 438, 197, 163, 115, 88, 61, 59, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
hs1, 1000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
```
hs1 coverage with red masking
```
GCA_028858775.2, 899305, 21726, 10156, 5661, 3505, 1841, 1214, 767, 598, 472, 350, 39, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
GCA_028878055.2, 830565, 14827, 5027, 2597, 1422, 797, 451, 274, 172, 125, 101, 39, 17, 17, 17, 14, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
GCA_028885625.2, 869086, 19628, 8368, 5136, 3248, 1802, 1197, 703, 386, 231, 67, 12, 10, 8, 8, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
GCA_028885655.2, 869411, 19661, 7975, 4826, 2971, 1862, 1257, 872, 519, 281, 152, 78, 46, 22, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
GCA_029281585.2, 893581, 27964, 13719, 8498, 5675, 3537, 2307, 1588, 945, 455, 266, 162, 109, 18, 18, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
GCA_029289425.2, 899301, 21498, 10191, 5251, 3047, 1575, 787, 268, 95, 71, 61, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
hg38, 925770, 10242, 3497, 1621, 779, 359, 133, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 37
hs1, 1000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
```
coverage is lower, but only by about half a percent.  

Ancestor sizes (lastz)
```
Anc0, 2, 2621303571, 4457, 0, 18106805
Anc1, 2, 2750525449, 1810, 21691233, 39686202
Anc2, 2, 2989900301, 1688, 40775105, 31488453
Anc3, 2, 2812845431, 4226, 39462021, 30997293
Anc4, 2, 2806166526, 1801, 30469142, 20823225
Anc5, 2, 2947834679, 5705, 21358897, 18137607
Anc6, 2, 2882020460, 1170, 21389405, 14483755
```
Ancestor sizes (red)
```
Anc0, 2, 2588464981, 1119, 0, 17651453
Anc1, 2, 2748056534, 1554, 21622578, 39511448
Anc2, 2, 2942365383, 821, 40085301, 29988501
Anc3, 2, 2805135350, 2100, 39352926, 30460457
Anc4, 2, 2803591636, 1453, 30309872, 20678654
Anc5, 2, 2895573863, 1041, 20910344, 16837025
Anc6, 2, 2871730368, 723, 21037788, 14363921
```
These seem in line with the coverage (slightly smaller) -- though a relatively larger reduction in number of ancestral contigs.

**Comment by glennhickey** [comment]
For the primates, lastz masking took 2474 cpu hours and 24 wall hours on the cluster, compared to roughly 16 cpu hours and 2 wall hours for red.  

Also, when trying to compute a 7-way alignment after dropping hg38, the lastz-masked alignment fails completely in bar.  The red-masked alignment runs fine. 

Conclusion: the improvements in speed and robustness are well worth making the switch, even if coverage drops a tiny bit in some cases (and this coverage drop is surely in extremely repetitive regions whose alignment is of questionable quality to begin with).

So I think I'm ready to merge, unless @benedictpaten you have any objections...

**Comment by glennhickey** [comment]
Here are some consolidated running times, as extracted from the log with ` grep Succ | awk '{print $5 "\t" $38}' | sort`.

They show modest speedup in 10-way but massive speedup in t2t apes. 

primates lastz
```
cactus_consolidated(Anc2):	15151.6102
cactus_consolidated(Anc3):	14124.735
cactus_consolidated(Anc4):	5456.394
cactus_consolidated(Anc5):	41010.9872
cactus_consolidated(Anc6):	6321.4298
```
primates red
```
cactus_consolidated(Anc2):	9308.8388
cactus_consolidated(Anc3):	9173.2259
cactus_consolidated(Anc4):	4775.8141
cactus_consolidated(Anc5):	6954.8602
cactus_consolidated(Anc6):	5804.2141
```
10-way lastz
```
cactus_consolidated(Anc02):	21001.3839
cactus_consolidated(Anc03):	51222.4407
cactus_consolidated(Anc04):	48323.943
cactus_consolidated(Anc05):	34137.6974
cactus_consolidated(Anc06):	30040.258
cactus_consolidated(Anc07):	25834.582
cactus_consolidated(Anc08):	38496.5654
cactus_consolidated(Anc09):	45839.7909
cactus_consolidated(Anc10):	11674.8884
```
10-way red
```
cactus_consolidated(Anc02):	20682.3916
cactus_consolidated(Anc03):	47745.1372
cactus_consolidated(Anc04):	50047.3168
cactus_consolidated(Anc05):	34607.4769
cactus_consolidated(Anc06):	30442.5855
cactus_consolidated(Anc07):	26893.5983
cactus_consolidated(Anc08):	37809.4971
cactus_consolidated(Anc09):	44850.9519
cactus_consolidated(Anc10):	11383.4624
```

**Comment by benedictpaten** [comment]
Brilliant. I think this is ready to merge.

**Pull request merged**
